package persistencias;
// Generated 2 jun 2024 19:24:53 by Hibernate Tools 5.4.33.Final

import java.math.BigDecimal;

/**
 * Carta generated by hbm2java
 */
public class Carta implements java.io.Serializable {

	private Integer idCarta;
	private Coleccion coleccion;
	private String nombreOriginal;
	private String nombreEspaniol;
	private String rareza;
	private Integer coste;
	private String color;
	private String tipo;
	private String png;
	private Integer seen;
	private BigDecimal alsa;
	private BigDecimal ata;
	private Integer picked;
	private Integer gp;
	private BigDecimal gpWr;

	public Carta() {
	}

	public Carta(Coleccion coleccion, String nombreOriginal, String nombreEspaniol, String rareza, Integer coste,
			String color, String tipo, String png, Integer seen, BigDecimal alsa, BigDecimal ata, Integer picked,
			Integer gp, BigDecimal gpWr) {
		this.coleccion = coleccion;
		this.nombreOriginal = nombreOriginal;
		this.nombreEspaniol = nombreEspaniol;
		this.rareza = rareza;
		this.coste = coste;
		this.color = color;
		this.tipo = tipo;
		this.png = png;
		this.seen = seen;
		this.alsa = alsa;
		this.ata = ata;
		this.picked = picked;
		this.gp = gp;
		this.gpWr = gpWr;
	}

	public Integer getIdCarta() {
		return this.idCarta;
	}

	public void setIdCarta(Integer idCarta) {
		this.idCarta = idCarta;
	}

	public Coleccion getColeccion() {
		return this.coleccion;
	}

	public void setColeccion(Coleccion coleccion) {
		this.coleccion = coleccion;
	}

	public String getNombreOriginal() {
		return this.nombreOriginal;
	}

	public void setNombreOriginal(String nombreOriginal) {
		this.nombreOriginal = nombreOriginal;
	}

	public String getNombreEspaniol() {
		return this.nombreEspaniol;
	}

	public void setNombreEspaniol(String nombreEspaniol) {
		this.nombreEspaniol = nombreEspaniol;
	}

	public String getRareza() {
		return this.rareza;
	}

	public void setRareza(String rareza) {
		this.rareza = rareza;
	}

	public Integer getCoste() {
		return this.coste;
	}

	public void setCoste(Integer coste) {
		this.coste = coste;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getPng() {
		return this.png;
	}

	public void setPng(String png) {
		this.png = png;
	}

	public Integer getSeen() {
		return this.seen;
	}

	public void setSeen(Integer seen) {
		this.seen = seen;
	}

	public BigDecimal getAlsa() {
		return this.alsa;
	}

	public void setAlsa(BigDecimal alsa) {
		this.alsa = alsa;
	}

	public BigDecimal getAta() {
		return this.ata;
	}

	public void setAta(BigDecimal ata) {
		this.ata = ata;
	}

	public Integer getPicked() {
		return this.picked;
	}

	public void setPicked(Integer picked) {
		this.picked = picked;
	}

	public Integer getGp() {
		return this.gp;
	}

	public void setGp(Integer gp) {
		this.gp = gp;
	}

	public BigDecimal getGpWr() {
		return this.gpWr;
	}

	public void setGpWr(BigDecimal gpWr) {
		this.gpWr = gpWr;
	}

}
