package persistencias;
// Generated 2 jun 2024 19:24:53 by Hibernate Tools 5.4.33.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Coleccion generated by hbm2java
 */
public class Coleccion implements java.io.Serializable {

	private String nombre;
	private int insertado;
	private Set mazos = new HashSet(0);
	private Set cartas = new HashSet(0);

	public Coleccion() {
	}

	public Coleccion(String nombre, int insertado) {
		this.nombre = nombre;
		this.insertado = insertado;
	}
	
	public Coleccion(String nombre) {
		this.nombre = nombre;
		
	}

	public Coleccion(String nombre, int insertado, Set mazos, Set cartas) {
		this.nombre = nombre;
		this.insertado = insertado;
		this.mazos = mazos;
		this.cartas = cartas;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getInsertado() {
		return this.insertado;
	}

	public void setInsertado(int insertado) {
		this.insertado = insertado;
	}

	public Set getMazos() {
		return this.mazos;
	}

	public void setMazos(Set mazos) {
		this.mazos = mazos;
	}

	public Set getCartas() {
		return this.cartas;
	}

	public void setCartas(Set cartas) {
		this.cartas = cartas;
	}

}
