package persistencias;
// Generated 27 may 2024 19:14:55 by Hibernate Tools 5.4.33.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Mazo generated by hbm2java
 */
public class Mazo implements java.io.Serializable {

	private Integer idMazo;
	private Usuario usuario;
	private Date fechaCreacion;
	private int cantidadCartas;
	private BigDecimal winrate;
	private Integer curvaMana;
	private Integer colorW;
	private Integer colorB;
	private Integer colorR;
	private Integer colorG;
	private Integer colorU;
	private Integer multiColor;
	private Integer colorless;
	private Integer criaturas;
	private Integer artefactos;
	private Integer instantaneos;
	private Integer comunes;
	private Integer infrecuentes;
	private Integer raras;
	private Integer legendarias;

	public Mazo() {
	}

	public Mazo(int cantidadCartas, BigDecimal winrate) {
		this.cantidadCartas = cantidadCartas;
		this.winrate = winrate;
	}

	public Mazo(Usuario usuario, Date fechaCreacion, int cantidadCartas, BigDecimal winrate, Integer curvaMana,
			Integer colorW, Integer colorB, Integer colorR, Integer colorG, Integer colorU, Integer multiColor,
			Integer colorless, Integer criaturas, Integer artefactos, Integer instantaneos, Integer comunes,
			Integer infrecuentes, Integer raras, Integer legendarias) {
		this.usuario = usuario;
		this.fechaCreacion = fechaCreacion;
		this.cantidadCartas = cantidadCartas;
		this.winrate = winrate;
		this.curvaMana = curvaMana;
		this.colorW = colorW;
		this.colorB = colorB;
		this.colorR = colorR;
		this.colorG = colorG;
		this.colorU = colorU;
		this.multiColor = multiColor;
		this.colorless = colorless;
		this.criaturas = criaturas;
		this.artefactos = artefactos;
		this.instantaneos = instantaneos;
		this.comunes = comunes;
		this.infrecuentes = infrecuentes;
		this.raras = raras;
		this.legendarias = legendarias;
	}

	public Integer getIdMazo() {
		return this.idMazo;
	}

	public void setIdMazo(Integer idMazo) {
		this.idMazo = idMazo;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public int getCantidadCartas() {
		return this.cantidadCartas;
	}

	public void setCantidadCartas(int cantidadCartas) {
		this.cantidadCartas = cantidadCartas;
	}

	public BigDecimal getWinrate() {
		return this.winrate;
	}

	public void setWinrate(BigDecimal winrate) {
		this.winrate = winrate;
	}

	public Integer getCurvaMana() {
		return this.curvaMana;
	}

	public void setCurvaMana(Integer curvaMana) {
		this.curvaMana = curvaMana;
	}

	public Integer getColorW() {
		return this.colorW;
	}

	public void setColorW(Integer colorW) {
		this.colorW = colorW;
	}

	public Integer getColorB() {
		return this.colorB;
	}

	public void setColorB(Integer colorB) {
		this.colorB = colorB;
	}

	public Integer getColorR() {
		return this.colorR;
	}

	public void setColorR(Integer colorR) {
		this.colorR = colorR;
	}

	public Integer getColorG() {
		return this.colorG;
	}

	public void setColorG(Integer colorG) {
		this.colorG = colorG;
	}

	public Integer getColorU() {
		return this.colorU;
	}

	public void setColorU(Integer colorU) {
		this.colorU = colorU;
	}

	public Integer getMultiColor() {
		return this.multiColor;
	}

	public void setMultiColor(Integer multiColor) {
		this.multiColor = multiColor;
	}

	public Integer getColorless() {
		return this.colorless;
	}

	public void setColorless(Integer colorless) {
		this.colorless = colorless;
	}

	public Integer getCriaturas() {
		return this.criaturas;
	}

	public void setCriaturas(Integer criaturas) {
		this.criaturas = criaturas;
	}

	public Integer getArtefactos() {
		return this.artefactos;
	}

	public void setArtefactos(Integer artefactos) {
		this.artefactos = artefactos;
	}

	public Integer getInstantaneos() {
		return this.instantaneos;
	}

	public void setInstantaneos(Integer instantaneos) {
		this.instantaneos = instantaneos;
	}

	public Integer getComunes() {
		return this.comunes;
	}

	public void setComunes(Integer comunes) {
		this.comunes = comunes;
	}

	public Integer getInfrecuentes() {
		return this.infrecuentes;
	}

	public void setInfrecuentes(Integer infrecuentes) {
		this.infrecuentes = infrecuentes;
	}

	public Integer getRaras() {
		return this.raras;
	}

	public void setRaras(Integer raras) {
		this.raras = raras;
	}

	public Integer getLegendarias() {
		return this.legendarias;
	}

	public void setLegendarias(Integer legendarias) {
		this.legendarias = legendarias;
	}

}
