package persistencias;
// Generated 27 may 2024 19:14:55 by Hibernate Tools 5.4.33.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer idUsuario;
	private String nombre;
	private String contrasenia;
	private Integer numDraft;
	private Set mazos = new HashSet(0);

	public Usuario() {
	}

	public Usuario(String nombre, String contrasenia) {
		this.nombre = nombre;
		this.contrasenia = contrasenia;
	}

	public Usuario(String nombre, String contrasenia, Integer numDraft, Set mazos) {
		this.nombre = nombre;
		this.contrasenia = contrasenia;
		this.numDraft = numDraft;
		this.mazos = mazos;
	}

	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getContrasenia() {
		return this.contrasenia;
	}

	public void setContrasenia(String contrasenia) {
		this.contrasenia = contrasenia;
	}

	public Integer getNumDraft() {
		return this.numDraft;
	}

	public void setNumDraft(Integer numDraft) {
		this.numDraft = numDraft;
	}

	public Set getMazos() {
		return this.mazos;
	}

	public void setMazos(Set mazos) {
		this.mazos = mazos;
	}

}
